<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <listeners>
    <listener class-name="Basecomponent.Listerners"/>
  </listeners>
  <test thread-count="5" parallel="tests" name="Error(failed)">
    <classes>
      <class name="p1.errorvalidation">
        <methods>
          <include name="closedDriver"/>
          <include name="LaunchApplication"/>
          <include name="LoginErrorValidation"/>
        </methods>
      </class> <!-- p1.errorvalidation -->
    </classes>
  </test> <!-- Error(failed) -->
  <test thread-count="5" parallel="tests" name="SubmitOrder(failed)">
    <classes>
      <class name="p1.StandAloneTest">
        <methods>
          <include name="closedDriver"/>
          <include name="orderhistory"/>
          <include name="LaunchApplication"/>
          <include name="submitordertest" invocation-numbers="0 1"/>
        </methods>
      </class> <!-- p1.StandAloneTest -->
    </classes>
  </test> <!-- SubmitOrder(failed) -->
</suite> <!-- Failed suite [Suite] -->
